### ISSUE TITLE
DNS validation for wildcard and non-wildcard domain

### ISSUE THREAD

**Issue by aik099** [acmephp/acmephp#186]
I have a config file like this:

```yaml
...

certificates:
  - domain: sub-domain.domain.td
    subject_alternative_names:
      - '*.sub-domain.domain.td'
    solver:
      name: dns
```

With that configuration ACME is expecting TXT string for `_acme-challenge.sub-domain.domain.td` to have 2 different values at the same time and of course it never works.

When changing DNS manually (with `dns` solver) I can make it work by specifying TXT entries on DNS server configuration in reverse order.

However, when using automated DNS solvers, like `route53` or `gandi` they just set last TXT entry and never change it.

It's likely a problem on Let's Encrypt, that it returns non-unique domain for validation.
