### ISSUE TITLE
Lost with documentation...

### ISSUE THREAD

**Issue by guldil** [acmephp/acmephp#195]
Hello,

I'm trying to get a certicate with Gandi, it's working but i can't find where is my cert file ?

My config.yml : 
````yaml
contact_email: support@xxxxxxxxxxxxxxxxx.fr

defaults:
  distinguished_name:
      country: FR
      locality: Lille
      organization_name: xxxxxxxxxxxxxxxxx
  solver: http

certificates:
  - domain: xxxxxxxxxxxxxxxxx.fr
    solver:
      name: gandi
      api_key: 'xxxxxxxxxxxxxxxxx'
````
Result : 
```shell
root@ubuntu35:~# php acmephp.phar run config.yml
Registering contact support@xxxxxxxxxxxxxxxxx.fr...
Loading account key pair...
Registering on the ACME server...
Account registered successfully!
Loading account key pair...
Requesting certificate order...
Solving challenge for domains...
Testing the challenge for domain xxxxxxxxxxxxxxxxx.fr...
Requesting authorization check for domain xxxxxxxxxxxxxxxxx.fr...
Cleaning up challenges for domains...
Requesting certificate for domain xxxxxxxxxxxxxxxxx.fr...
Loading account key pair...
Certificate requested successfully!
Installing certificate for domain xxxxxxxxxxxxxxxxx.fr...
````
Please help :)

Guldil
