### ISSUE TITLE
http-file solver not working

### ISSUE THREAD

**Issue by wayne-thorley** [acmephp/acmephp#201]
Using a yml config file I have set the solver to `http-file` with the `local` adapter and supplied a `root` path. Yet when i run `php acmephp.phar run mydomain.yml` it only runs as far as registering the account:

```
Registering contact ...
Loading account key pair...  
Registering on the ACME server...
Account registered successfully!
```

That's all. It doesn't attempt to request certs and doesn't output any error messages.
Looking in `/src/Core/Challenge/Http/FilesystemSolver.php` the function on line 77:

```
    public function solve(AuthorizationChallenge $authorizationChallenge)
    {
        $checkPath = $this->extractor->getCheckPath($authorizationChallenge);
        $checkContent = $this->extractor->getCheckContent($authorizationChallenge);

        $this->filesystem->write($checkPath, $checkContent);
    }
```

looks like it should be writing the file and solving the challenge automatically but it's like it's not even attempting this step.

Is there anything I'm missing...?

Config below:

```
contact_email: myemail@mydomain.com

defaults:
  distinguished_name:
      country: GB
      state: England
      locality: Manchester
      organization_name: My Company
  solver:
    name: http-file
    adapter: local
    root: /home/devoluti/public_html

certificates:
  - domain: mydomain.com
```
