### ISSUE TITLE
New Resolver - How Do I Pass API Key

### ISSUE THREAD

**Issue by programster** [acmephp/acmephp#241]
I'm trying to add support for using DigitalOcean as a DNS resolver ([GitHub Branch](https://github.com/programster/acmephp/tree/add-digital-ocean-dns-resolver)), and I managed to get it working apart from the fact that I wasn't able to have the API key passed through from the YAML configuration file. Here is an example YAML config file:

```yaml
contact_email: myEmail@gmail.com
key_type: RSA

defaults:
  distinguished_name:
      country: France
      locality: Paris
      organization_name: MyOrgName

certificates:
  - domain: test.mydomain.com
    solver: 
      name: digitalocean
      api_key: myApiKeyGoesHere
    subject_alternative_names:
      - www.mydomain.com
  ```

For now I am having to hardcode it as shown below:

![Selection_148](https://user-images.githubusercontent.com/5709838/128350667-0ceeb727-5041-48a4-86de-ed8b61b46cea.png)

I have the strong suspicion I am just configurting my `services.xml` file incorrectly. The changes are shown below:

![Selection_149](https://user-images.githubusercontent.com/5709838/128350810-b4f2a0bc-08ba-4d1c-85db-2b4e370b373b.png)

If I have `apiKey` in there, that will come through. If I take it out, then I just end up with a blank string.

### Question
What step do I need to perform to get the `api_key` to flow in through from the YAML configuration?

![Selection_150](https://user-images.githubusercontent.com/5709838/128351050-f6633184-6b07-437c-bc1a-6365c8360ad7.png)
