### ISSUE TITLE
Monitoring Slack does not work

### ISSUE THREAD

**Issue by Sh1nto** [acmephp/acmephp#47]
I have the following code in .acmephp/acmephp.conf

```
monitoring:
    slack:
        token: xxxxxxxxxx
        channel: #general
        #username: Acme PHP
        #level: info      # By default, on every CRON for slack handler
```

When executing the monitoring Test i get:
```
root:~# php -f acmephp.phar monitoring-test
Loading monitoring configuration...


  [AcmePhp\Cli\Exception\AcmeCliException]
  The Slack channel (key "channel") is required in the slack monitoring alert handler.


monitoring-test [<level>]
```

I'm using Version: Acme PHP - Let's Encrypt client 1.0.0-dev
