### ISSUE TITLE
acmephp monitoring-test questions/problems

### ISSUE THREAD

**Issue by fabbrikk** [acmephp/acmephp#66]
When calling
`acmephp monitoring-test`
I can see this output
```
Loading monitoring configuration...  
Triggering monitoring on "error" level...  
Triggered successfully  
You should have been alerted 
```
but no email is sent.

My acmephp.conf (monitoring part) is the following:
```
###################################################################
# Monitoring
#
# This section let you configure a simple monitoring mechanism that
# will warn you if an error occurs during a CRON job.
#

#monitoring: ~   # Monitoring is disabled by default

# You can enabled it by configuring at least one alert handler.
# You can change the default handler level to decide when to be alerted
# (only when an error occurs or every time the CRON is started).
monitoring:
    email:
        to: xxxxx@xxxxx.xxx
        host: smtp.xxxxxxx.xxxx
        port: 587
        username: userxxxx
        password: passxxxx
        subject: Error during Acme PHP CRON renewal
        encryption: TLS
        level: info
#
#    slack:
#        token: your_token
#        channel: general   # Channel name without hashtag
#        # username: Acme PHP
#        # level: info      # By default, on every CRON for slack handler
```
How can i test email error/info monitoring?
With the 'info' level setting, commands like theese
```
acmephp check -s http domain.xxxxx
acmephp request domain.xxxxx
acmephp request --force domain.xxxxx
```
should generate email report?
Thanks for your support.
